### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AShepelevv** [AShepelevv/astro.notebook#89]
- [x] Вывод точек Лагранжа
- [x] Вывод закона Стефана Больцмана
- [x] Вывод смещения Вина
- [x] Вывод приближения Вина
- [x] Вывод приближения Релея-Джинса
- [x] Вывод уравнения Каплера
- [x] Вывод 3его закона Кеплера (нужно дописать общий вид)
- [x] Вывод интеграла энергии
- [x] Вывод первой космической
- [x] Вывод ЗСМИ
- [x] Вывод формулы для потенциальной энергии
- [ ] Вывод преобразований Лоренца 
- [x] Вывод сферики еще
- [x] Скалярное произведение
- [x] Векторное произведение
- [x] Смешанное произведение
- [x] Выводы в эллипсе
- [x] Написать про полное затмение
- [x] Уравнение прямой на плоскости
- [x] Уравнение плоскости
- [ ] Энергия излучения. (Прочитал, так и не понял, как связаны и что такое яркость и интегральная яркость) Еще нужно нафиг убрать оттуда индекс е, он не нужен.
- [x] Вывод формулы для фазы

- [x] Написать про секториальную скорость и связь со 2 законом Кеплера
- [x] Параллактический эллипс
- [x] Собственное движение

- [x] Вывод  \lambda/D для щели
- [x] Закон Снеллиуса
- [x] Вывод формулы тонкой линзы
- [ ] Спектр. Уровни энергии в атоме. Фотоэффект
- [ ] Профиль линии излучения
- [ ] Линии поглощения
- [ ] Диаграмма направленноти радио телескопа. Радиотелескоп
- [ ] Нейтринный детектор
- [ ] Период полураспада
- [ ] Поляроид
- [x] Высота атмосферы: однородной, изобарической
- [ ] Дифф. предел дифф. решетки и призмы
- [ ] Построение изображения в фокальной плоскости
- [ ] Незaтененное поле зрения телескопа
- [x] Поиск центра окружности по дуге
- [x] Космологическое красное смещение. Космология. (Переписать красное смещение в эффекте Доплера, потому что оно так не космологическое.
